# Generated by Django 2.2.7 on 2019-11-20 22:20

from django.db import migrations
# import sys
# sys.path.insert(0, '/adventure')
from adventure.world_gen import World
# from .models import Room

def populate_database(apps, schema_editor):
    """
    Creates a procedurally generated world then adds the constituent rooms to the DB.
    """
    

    w = World()
    width = 51
    height = 51
    w.depth_first_room_generator(width, height)

    for i in range(len(w.grid)):
        for j in range(len(w.grid[i])):
            if w.grid[i][j] != None:
                # It's a room object! let's put it into the database!
                obj = w.grid[i][j]
                new_room = apps.get_model('adventure', 'Room')
                
                new_room.id = obj.id
                new_room.title=obj.name,
                new_room.description=obj.description
                new_room.n_to = obj.n_to.id
                new_room.s_to = obj.s_to.id
                new_room.e_to = obj.e_to.id
                new_room.w_to = obj.w_to.id
                new_room.x = obj.x
                new_room.y = obj.y
                new_room.save()







class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_database)
    ]
